### ISSUE TITLE
FileNotFoundException: armeabi-v7a/cjdroute-init

### ISSUE THREAD

**Issue by sssemil** [BerlinMeshnet/cjdns-android#59]
Where can I find cjdroute-init? @benhylau  

```
E/CjdnsVpnService: Failed to initialize TUN interface
java.io.FileNotFoundException: armeabi-v7a/cjdroute-init
at android.content.res.AssetManager.openAsset(Native Method)
at android.content.res.AssetManager.open(AssetManager.java:331)
at android.content.res.AssetManager.open(AssetManager.java:305)
at berlin.meshnet.cjdns.CjdrouteConf.copyExecutable(CjdrouteConf.java:293)
at berlin.meshnet.cjdns.CjdrouteConf.access$100(CjdrouteConf.java:31)
at berlin.meshnet.cjdns.CjdrouteConf$1.call(CjdrouteConf.java:107)
at berlin.meshnet.cjdns.CjdrouteConf$1.call(CjdrouteConf.java:90)
at rx.Observable$1.call(Observable.java:144)
at rx.Observable$1.call(Observable.java:136)
...
```

**Comment by ghost** [comment]
I lost it with my laptop and have to rewrite it -- will get to it eventually in the next week

**Comment by sssemil** [comment]
Benedict probably has it. He used it in latest commits to fuckit-hackit branch.

**Comment by benhylau** [comment]
@sssemil I have the binary on my laptop only. By the way, the hack branch is superseded by this: https://github.com/hyperboria/android/pull/58 Though regardless of which branch, I am the only one who can build the APKs at the moment because of these local binaries. Let's wait for @lgierth to push his changes then I can doc the full build process?

**Comment by sssemil** [comment]
@benhylau cool. So, it works on lollipop?

**Comment by benhylau** [comment]
@sssemil yup worked on all the 4.0+ we tried on (like 8 of them) only failed on the Nexus 5x because we didn't compile for arm64, @lgierth gonna enable that too

**Comment by sssemil** [comment]
Hi @benhylau and @lgierth, any progress or anything you need help with?

**Comment by benhylau** [comment]
Sorry for the delay. It's up now: https://github.com/hyperboria/android/issues/47#issuecomment-252162293

**Comment by kylerchin** [comment]
My google pixel crashes on opening the app.

**Comment by benhylau** [comment]
`adb logcat`?
