### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kylerchin** [BerlinMeshnet/cjdns-android#62]
I keep getting this error when compiling:

```
    Searching for SECCOMP
Total build time: 43697ms.
/home/kyler/code/android-cjdns/cjdns/node_build/builder.js:485
        if (err) { throw err; }
                   ^

Error: gcc -c -x cpp-output -o build_linux/memory_Allocator_c.o -std=c99 -Wall -Wextra -Werror    -Wno-pointer-sign -pedantic -D linux=1 -D CJD_PACKAGE_VERSION="cjdns-0.3-3823-g7f5caec" -Wno-unused-parameter -D Log_DEBUG -g -D NumberCompress_TYPE=v3x5x8 -D Identity_CHECK=1 -D Allocator_USE_CANARIES=1 -D PARANOIA=1 -DHAS_ETH_INTERFACE=1 -fPIE -Dandroid=1 -fno-stack-protector -fstack-protector-all -Wstack-protector -O3 build_linux/memory_Allocator_c.o.i

memory/Allocator.c: In function 'Allocator_new':
memory/Allocator.c:790:51: error: integer constant is too large for its type [-Werror]
         .canary = (unsigned long) Constant_rand64(),
                                               ^
memory/Allocator.c:791:55: error: integer constant is too large for its type [-Werror]
         .nextCanary = (unsigned long) Constant_rand64(),
                                                   ^
cc1: all warnings being treated as errors

    at error (/home/kyler/code/android-cjdns/cjdns/node_build/builder.js:53:15)
   at /home/kyler/code/android-cjdns/cjdns/node_build/builder.js:122:22
    at /home/kyler/code/android-cjdns/cjdns/node_build/builder.js:92:13
    at ChildProcess.<anonymous> (/home/kyler/code/android-cjdns/cjdns/tools/lib/Semaphore.js:7:30)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:852:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)

real    0m45.007s
user    1m27.170s
sys 0m6.970s
cp: cannot stat 'cjdroute': No such file or directory
Copying armeabi-v7a binary failed, non zero status returned - 1
```

Please send help.

P.S. My new site is cjdns compatible.
[h.glitchedpixels.com](http://h.glitchedpixels.com)

**Comment by ghost** [comment]
I am not a cjdns user, but the error message explains itself, `cp: cannot stat 'cjdroute': No such file or directory`, this file/dir is missing.

**Comment by benhylau** [comment]
The app isn't in working shape yet. Will get on it soon.
