### ISSUE TITLE
Execution of cjdroute is not yet supported for your API level

### ISSUE THREAD

**Issue by IvanOnishchenko** [BerlinMeshnet/cjdns-android#73]
When I try to on toggle on Android 7, app is closing and get error:
FATAL EXCEPTION: main
                                                                      Process: berlin.meshnet.cjdns, PID: 15387
                                                                      java.lang.RuntimeException: Unable to create service berlin.meshnet.cjdns.CjdnsService: java.lang.UnsupportedOperationException: Execution of cjdroute is not yet supported for your API level
                                                                          at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
                                                                          at android.app.ActivityThread.-wrap6(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1732)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                       Caused by: java.lang.UnsupportedOperationException: Execution of cjdroute is not yet supported for your API level
                                                                          at berlin.meshnet.cjdns.Cjdroute$Default.execute(Cjdroute.java:110)
                                                                          at berlin.meshnet.cjdns.CjdnsService.onCreate(CjdnsService.java:81)
                                                                          at android.app.ActivityThread.handleCreateService(ActivityThread.java:3534)
                                                                          at android.app.ActivityThread.-wrap6(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1732) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by kylerchin** [comment]
Me too.

**Comment by vikulin** [comment]
Caused by https://github.com/hyperboria/android/issues/72
